services:
  - type: web
    name: crazy-musics-admin
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        value: Admin777@gmail.com
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_NAME
        value: Admin
      - key: NODE_ENV
        value: production
